import fs from 'node:fs/promises';
import path from 'node:path';

const ROOT = process.cwd();
const config = JSON.parse(await fs.readFile(path.join(ROOT, 'README.config.json'), 'utf8'));
await fs.mkdir(path.join(ROOT, 'assets'), { recursive: true });

const escapeXml = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&apos;');

const profiles = config.profiles.map((profile) => `- [**${profile.label}**](${profile.url}) — ${profile.role}`).join('\n');
const workflowRows = config.workflow.map((item) => `| ${item.step} | **${item.label}** | ${item.description} |`).join('\n');

const readme = `<!--\nREADME generated from README.config.json.\nEdit the config, then run: npm run readme:build\n-->\n\n<p align="center">\n  <img src="./assets/readme-hero.svg" alt="${config.title} — ${config.subtitle}" width="100%" />\n</p>\n\n<p align="center">\n  <a href="${config.website}"><img alt="Website" src="https://img.shields.io/badge/Website-DeonteWatts.Space-00FFFF?style=for-the-badge&labelColor=050505"></a>\n  <a href="https://orcid.org/${config.orcid}"><img alt="ORCID" src="https://img.shields.io/badge/ORCID-${config.orcid}-BD00FF?style=for-the-badge&labelColor=050505"></a>\n  <img alt="Status" src="https://img.shields.io/badge/System-${config.status}-FFD166?style=for-the-badge&labelColor=050505">\n</p>\n\n# ${config.title}\n\n**${config.name}** · ${config.affiliation}  \n${config.subtitle}\n\n${config.mission}\n\n## Network Nodes\n\n${profiles}\n\n## Archival Protocol\n\n| Step | Protocol | Function |\n|---:|---|---|\n${workflowRows}\n\n## Configure This README Front Page\n\nEdit \`README.config.json\`, then regenerate:\n\n\`\`\`bash\nnpm run readme:build\n\`\`\`\n\nThis README uses GitHub-safe Markdown plus an animated SVG asset. Keep full browser JavaScript and mouse-tilt effects inside the website app, not inside \`README.md\`.\n\n## Repository Map\n\n\`\`\`txt\nassets/readme-hero.svg        README visual front-page header\nREADME.config.json            Editable content/theme/profile config\nscripts/generate-readme.mjs   README + SVG renderer\nmetadata/                     DOI, ORCID, Dublin Core, and DataCite records\nmanuscript/                   LaTeX manuscript sources\nbibliography/                 BibTeX, RIS, and CSL citation records\n\`\`\`\n`;

const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1100" height="620" viewBox="0 0 1100 620" role="img" aria-labelledby="title desc">
<title id="title">${escapeXml(config.title)} repository front page hero</title>
<desc id="desc">Holographic README header for ${escapeXml(config.name)}.</desc>
<defs><linearGradient id="holo" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="#00FFFF"/><stop offset="52%" stop-color="#FF00FF"/><stop offset="100%" stop-color="#BD00FF"/></linearGradient><radialGradient id="bg" cx="50%" cy="38%" r="75%"><stop offset="0%" stop-color="#BD00FF" stop-opacity="0.24"/><stop offset="42%" stop-color="#00FFFF" stop-opacity="0.1"/><stop offset="100%" stop-color="#050505"/></radialGradient><pattern id="grid" width="34" height="34" patternUnits="userSpaceOnUse"><path d="M34 0H0V34" fill="none" stroke="#fff" stroke-opacity=".055"/></pattern><style>.bg{fill:url(#bg)}.grid{fill:url(#grid)}.card{fill:rgba(255,255,255,.055);stroke:url(#holo);stroke-opacity:.5}.brand{font:600 14px monospace;letter-spacing:6px;fill:#00FFFF}.title{font:800 72px Arial,sans-serif;letter-spacing:3px;fill:url(#holo)}.sub{font:400 22px monospace;fill:#d8d8ff}.body{font:400 20px Arial,sans-serif;fill:#f6f6ff}.mono{font:600 16px monospace;fill:#FFD166}.scan{stroke:url(#holo);stroke-width:3;opacity:.7}@media (prefers-reduced-motion:no-preference){.scan{animation:scan 4s linear infinite}@keyframes scan{0%{transform:translateY(-210px)}100%{transform:translateY(210px)}}}</style></defs><rect class="bg" width="1100" height="620" rx="34"/><rect class="grid" width="1100" height="620" rx="34"/><rect x="45" y="42" width="1010" height="536" rx="30" class="card"/><line x1="45" x2="1055" y1="310" y2="310" class="scan"/><text x="550" y="104" text-anchor="middle" class="brand">${escapeXml(config.brand)}</text><text x="550" y="194" text-anchor="middle" class="title">${escapeXml(config.title)}</text><text x="550" y="235" text-anchor="middle" class="sub">${escapeXml(config.subtitle)}</text><text x="550" y="292" text-anchor="middle" class="body">Public research identity hub for manuscripts, citations, DOI releases,</text><text x="550" y="322" text-anchor="middle" class="body">authority profiles, and open-science publishing workflows.</text><text x="550" y="364" text-anchor="middle" class="mono">ORCID: ${escapeXml(config.orcid)} · SYSTEM: ${escapeXml(config.status).toUpperCase()}</text></svg>`;

await fs.writeFile(path.join(ROOT, 'README.md'), readme);
await fs.writeFile(path.join(ROOT, 'assets', 'readme-hero.svg'), svg);
